sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=pfragoso/flask-api

stages:
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
      script:
      - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"    
      - docker build --rm --tag "$DOCKER_IMAGE":"$TRAVIS_COMMIT" .
      - docker build --rm --tag "$DOCKER_IMAGE":latest .
      - docker images
      - docker run --rm "$DOCKER_IMAGE":"$TRAVIS_COMMIT" yarn run test
      - docker run --rm --detach --publish 127.0.0.1:5000:5000 "$DOCKER_IMAGE":"$TRAVIS_COMMIT"
      - docker ps
      - sleep 5 
      - curl -I http://127.0.0.1:5000/kubernetes
      - docker push "$DOCKER_IMAGE":"$TRAVIS_COMMIT"  
      - docker push "$DOCKER_IMAGE":latest  
    - stage: deploy
      script: ./scripts/deploy.sh
